{
 "title": "Pizza Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "latency", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pizza Revenue",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 0 },
   "targets": [
    { "expr": "pizzaRevenue_total", "legendFormat": "__auto" },
    { "expr": "revenueLost_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 14, "y": 0 },
   "targets": [
    { "expr": "pizzasPurchased_total", "legendFormat": "__auto" },
    { "expr": "orderFailures_total", "legendFormat": "__auto" },
    {}
   ]
  },
  {
   "title": "CPU %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpuUsage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memoryUsage", "legendFormat": "{{Memory %}}" }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "increase(requests_total[1m])", "legendFormat": "__auto" },
    {
     "expr": "increase(requests_put_total[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(requests_get_total[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(requests_post_total[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(requests_delete_total[1m])",
     "legendFormat": "__auto"
    },
    { "expr": "rate(requests_put_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "targets": [
    { "expr": "activeusers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Authentication",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 8, "y": 10 },
   "targets": [
    { "expr": "authSuccess", "legendFormat": "__auto" },
    {
     "expr": "increase(authSuccess_total[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(authFailure_total[1m])",
     "legendFormat": "__auto"
    },
    { "expr": "authFailure_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"http\"} | json"
    }
   ]
  },
  {
   "title": "DB Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"db-query\"} |= `` | logfmt"
    }
   ]
  },
  {
   "title": "Factory Orders",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"FactoryOrder\"}"
    }
   ]
  },
  {
   "title": "Factory Response",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"FactoryResponse\"}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{type=\"Error\"}"
    }
   ]
  }
 ]
}